#NORMAL
execute @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=rock_tunnel,score_mig_crouch_timer_min=890,score_mig_crouch_timer=900] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /summon creeper ~ ~ ~ {CustomName:"§aCreeper",CustomNameVisible:0}
execute @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=rock_tunnel,score_mig_crouch_timer_min=890,score_mig_crouch_timer=900] ~ ~ ~ detect ~ ~-1 ~ cobblestone /summon creeper ~ ~ ~ {CustomName:"§aCreeper",CustomNameVisible:0}
execute @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=rock_tunnel,score_mig_crouch_timer_min=890,score_mig_crouch_timer=900] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=rock_tunnel,score_mig_crouch_timer_min=890,score_mig_crouch_timer=900] {"text":"§aCreeper Spawned"}
execute @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=rock_tunnel,score_mig_crouch_timer_min=890,score_mig_crouch_timer=900] ~ ~ ~ detect ~ ~-1 ~ cobblestone /tellraw @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=rock_tunnel,score_mig_crouch_timer_min=890,score_mig_crouch_timer=900] {"text":"§aCreeper Spawned"}
execute @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=rock_tunnel,score_mig_sprint_timer_min=890,score_mig_sprint_timer=900] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /summon creeper ~ ~ ~ {CustomName:"§aCreeper",CustomNameVisible:0}
execute @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=rock_tunnel,score_mig_sprint_timer_min=890,score_mig_sprint_timer=900] ~ ~ ~ detect ~ ~-1 ~ cobblestone /summon creeper ~ ~ ~ {CustomName:"§aCreeper",CustomNameVisible:0}
execute @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=rock_tunnel,score_mig_sprint_timer_min=890,score_mig_sprint_timer=900] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=rock_tunnel,score_mig_sprint_timer_min=890,score_mig_sprint_timer=900] {"text":"§aCreeper Spawned"}
execute @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=rock_tunnel,score_mig_sprint_timer_min=890,score_mig_sprint_timer=900] ~ ~ ~ detect ~ ~-1 ~ cobblestone /tellraw @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=rock_tunnel,score_mig_sprint_timer_min=890,score_mig_sprint_timer=900] {"text":"§aCreeper Spawned"}
execute @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=rock_tunnel,score_mig_walk_timer_min=890,score_mig_walk_timer=900] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /summon creeper ~ ~ ~ {CustomName:"§aCreeper",CustomNameVisible:0}
execute @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=rock_tunnel,score_mig_walk_timer_min=890,score_mig_walk_timer=900] ~ ~ ~ detect ~ ~-1 ~ cobblestone /summon creeper ~ ~ ~ {CustomName:"§aCreeper",CustomNameVisible:0}
execute @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=rock_tunnel,score_mig_walk_timer_min=890,score_mig_walk_timer=900] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=rock_tunnel,score_mig_walk_timer_min=890,score_mig_walk_timer=900] {"text":"§aCreeper Spawned"}
execute @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=rock_tunnel,score_mig_walk_timer_min=890,score_mig_walk_timer=900] ~ ~ ~ detect ~ ~-1 ~ cobblestone /tellraw @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=rock_tunnel,score_mig_walk_timer_min=890,score_mig_walk_timer=900] {"text":"§aCreeper Spawned"}
scoreboard players add @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=rock_tunnel,score_mig_crouch_timer_min=890,score_mig_crouch_timer=900] mig_crouch_timer 10
scoreboard players add @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=rock_tunnel,score_mig_sprint_timer_min=890,score_mig_sprint_timer=900] mig_sprint_timer 10
scoreboard players add @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=rock_tunnel,score_mig_walk_timer_min=890,score_mig_walk_timer=900] mig_walk_timer 10
#ATTRACT
execute @a[score_mig_attractrepel_min=1,tag=rock_tunnel,score_mig_crouch_timer_min=800,score_mig_crouch_timer=900] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /summon creeper ~ ~ ~ {CustomName:"§aCreeper",CustomNameVisible:0}
execute @a[score_mig_attractrepel_min=1,tag=rock_tunnel,score_mig_crouch_timer_min=800,score_mig_crouch_timer=900] ~ ~ ~ detect ~ ~-1 ~ cobblestone /summon creeper ~ ~ ~ {CustomName:"§aCreeper",CustomNameVisible:0}
execute @a[score_mig_attractrepel_min=1,tag=rock_tunnel,score_mig_crouch_timer_min=800,score_mig_crouch_timer=900] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel_min=1,tag=rock_tunnel,score_mig_crouch_timer_min=800,score_mig_crouch_timer=900] {"text":"§aCreeper Spawned"}
execute @a[score_mig_attractrepel_min=1,tag=rock_tunnel,score_mig_crouch_timer_min=800,score_mig_crouch_timer=900] ~ ~ ~ detect ~ ~-1 ~ cobblestone /tellraw @a[score_mig_attractrepel_min=1,tag=rock_tunnel,score_mig_crouch_timer_min=800,score_mig_crouch_timer=900] {"text":"§aCreeper Spawned"}
execute @a[score_mig_attractrepel_min=1,tag=rock_tunnel,score_mig_sprint_timer_min=800,score_mig_sprint_timer=900] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /summon creeper ~ ~ ~ {CustomName:"§aCreeper",CustomNameVisible:0}
execute @a[score_mig_attractrepel_min=1,tag=rock_tunnel,score_mig_sprint_timer_min=800,score_mig_sprint_timer=900] ~ ~ ~ detect ~ ~-1 ~ cobblestone /summon creeper ~ ~ ~ {CustomName:"§aCreeper",CustomNameVisible:0}
execute @a[score_mig_attractrepel_min=1,tag=rock_tunnel,score_mig_sprint_timer_min=800,score_mig_sprint_timer=900] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel_min=1,tag=rock_tunnel,score_mig_sprint_timer_min=800,score_mig_sprint_timer=900] {"text":"§aCreeper Spawned"}
execute @a[score_mig_attractrepel_min=1,tag=rock_tunnel,score_mig_sprint_timer_min=800,score_mig_sprint_timer=900] ~ ~ ~ detect ~ ~-1 ~ cobblestone /tellraw @a[score_mig_attractrepel_min=1,tag=rock_tunnel,score_mig_sprint_timer_min=800,score_mig_sprint_timer=900] {"text":"§aCreeper Spawned"}
execute @a[score_mig_attractrepel_min=1,tag=rock_tunnel,score_mig_walk_timer_min=800,score_mig_walk_timer=900] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /summon creeper ~ ~ ~ {CustomName:"§aCreeper",CustomNameVisible:0}
execute @a[score_mig_attractrepel_min=1,tag=rock_tunnel,score_mig_walk_timer_min=800,score_mig_walk_timer=900] ~ ~ ~ detect ~ ~-1 ~ cobblestone /summon creeper ~ ~ ~ {CustomName:"§aCreeper",CustomNameVisible:0}
execute @a[score_mig_attractrepel_min=1,tag=rock_tunnel,score_mig_walk_timer_min=800,score_mig_walk_timer=900] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel_min=1,tag=rock_tunnel,score_mig_walk_timer_min=800,score_mig_walk_timer=900] {"text":"§aCreeper Spawned"}
execute @a[score_mig_attractrepel_min=1,tag=rock_tunnel,score_mig_walk_timer_min=800,score_mig_walk_timer=900] ~ ~ ~ detect ~ ~-1 ~ cobblestone /tellraw @a[score_mig_attractrepel_min=1,tag=rock_tunnel,score_mig_walk_timer_min=800,score_mig_walk_timer=900] {"text":"§aCreeper Spawned"}
scoreboard players add @a[score_mig_attractrepel_min=1,tag=rock_tunnel,score_mig_crouch_timer_min=800,score_mig_crouch_timer=900] mig_crouch_timer 100
scoreboard players add @a[score_mig_attractrepel_min=1,tag=rock_tunnel,score_mig_sprint_timer_min=800,score_mig_sprint_timer=900] mig_sprint_timer 100
scoreboard players add @a[score_mig_attractrepel_min=1,tag=rock_tunnel,score_mig_walk_timer_min=800,score_mig_walk_timer=900] mig_walk_timer 100
#REPEL
execute @a[score_mig_attractrepel=-1,tag=rock_tunnel,score_mig_crouch_timer_min=895,score_mig_crouch_timer=900] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /summon creeper ~ ~ ~ {CustomName:"§aCreeper",CustomNameVisible:0}
execute @a[score_mig_attractrepel=-1,tag=rock_tunnel,score_mig_crouch_timer_min=895,score_mig_crouch_timer=900] ~ ~ ~ detect ~ ~-1 ~ cobblestone /summon creeper ~ ~ ~ {CustomName:"§aCreeper",CustomNameVisible:0}
execute @a[score_mig_attractrepel=-1,tag=rock_tunnel,score_mig_crouch_timer_min=895,score_mig_crouch_timer=900] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel=-1,tag=rock_tunnel,score_mig_crouch_timer_min=895,score_mig_crouch_timer=900] {"text":"§aCreeper Spawned"}
execute @a[score_mig_attractrepel=-1,tag=rock_tunnel,score_mig_crouch_timer_min=895,score_mig_crouch_timer=900] ~ ~ ~ detect ~ ~-1 ~ cobblestone /tellraw @a[score_mig_attractrepel=-1,tag=rock_tunnel,score_mig_crouch_timer_min=895,score_mig_crouch_timer=900] {"text":"§aCreeper Spawned"}
execute @a[score_mig_attractrepel=-1,tag=rock_tunnel,score_mig_sprint_timer_min=895,score_mig_sprint_timer=900] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /summon creeper ~ ~ ~ {CustomName:"§aCreeper",CustomNameVisible:0}
execute @a[score_mig_attractrepel=3,tag=rock_tunnel,score_mig_sprint_timer_min=666,score_mig_sprint_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~-1 ~ cobblestone /summon creeper ~ ~ ~ {CustomName:"§b§l✧§aCreeper§b§l✧",CustomNameVisible:0,PersistenceRequired:1,Tags:["shiny_1"],DeathLootTable:"pokeserver:mobs_in_grass/shiny/creeper0}
execute @a[score_mig_attractrepel=-1,tag=rock_tunnel,score_mig_sprint_timer_min=895,score_mig_sprint_timer=900] ~ ~ ~ detect ~ ~-1 ~ cobblestone /summon creeper ~ ~ ~ {CustomName:"§aCreeper",CustomNameVisible:0}
execute @a[score_mig_attractrepel=-1,tag=rock_tunnel,score_mig_sprint_timer_min=895,score_mig_sprint_timer=900] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel=-1,tag=rock_tunnel,score_mig_sprint_timer_min=895,score_mig_sprint_timer=900] {"text":"§aCreeper Spawned"}
execute @a[score_mig_attractrepel=-1,tag=rock_tunnel,score_mig_sprint_timer_min=895,score_mig_sprint_timer=900] ~ ~ ~ detect ~ ~-1 ~ cobblestone /tellraw @a[score_mig_attractrepel=-1,tag=rock_tunnel,score_mig_sprint_timer_min=895,score_mig_sprint_timer=900] {"text":"§aCreeper Spawned"}
execute @a[score_mig_attractrepel=-1,tag=rock_tunnel,score_mig_walk_timer_min=895,score_mig_walk_timer=900] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /summon creeper ~ ~ ~ {CustomName:"§aCreeper",CustomNameVisible:0}
execute @a[score_mig_attractrepel_min=1,tag=rock_tunnel,score_mig_walk_timer_min=800,score_mig_walk_timer=900] ~ ~ ~ detect ~ ~-1 ~ cobblestone /summon creeper ~ ~ ~ {CustomName:"§aCreeper",CustomNameVisible:0}
execute @a[score_mig_attractrepel=-1,tag=rock_tunnel,score_mig_walk_timer_min=895,score_mig_walk_timer=900] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel=-1,tag=rock_tunnel,score_mig_walk_timer_min=895,score_mig_walk_timer=900] {"text":"§aCreeper Spawned"}
execute @a[score_mig_attractrepel=-1,tag=rock_tunnel,score_mig_walk_timer_min=895,score_mig_walk_timer=900] ~ ~ ~ detect ~ ~-1 ~ cobblestone /tellraw @a[score_mig_attractrepel=-1,tag=rock_tunnel,score_mig_walk_timer_min=895,score_mig_walk_timer=900] {"text":"§aCreeper Spawned"}
scoreboard players add @a[score_mig_attractrepel=-1,tag=rock_tunnel,score_mig_crouch_timer_min=895,score_mig_crouch_timer=900] mig_crouch_timer 10
scoreboard players add @a[score_mig_attractrepel=-1,tag=rock_tunnel,score_mig_sprint_timer_min=895,score_mig_sprint_timer=900] mig_sprint_timer 10
scoreboard players add @a[score_mig_attractrepel=-1,tag=rock_tunnel,score_mig_walk_timer_min=895,score_mig_walk_timer=900] mig_walk_timer 10
#SHINY
execute @a[score_mig_attractrepel=3,tag=rock_tunnel,score_mig_crouch_timer_min=666,score_mig_crouch_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /summon creeper ~ ~ ~ {CustomName:"§b§l✧§aCreeper§b§l✧",CustomNameVisible:0,PersistenceRequired:1,Tags:["shiny_1"],DeathLootTable:"pokeserver:mobs_in_grass/shiny/creeper0}
execute @a[score_mig_attractrepel=3,tag=rock_tunnel,score_mig_crouch_timer_min=666,score_mig_crouch_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~-1 ~ cobblestone /summon creeper ~ ~ ~ {CustomName:"§b§l✧§aCreeper§b§l✧",CustomNameVisible:0,PersistenceRequired:1,Tags:["shiny_1"],DeathLootTable:"pokeserver:mobs_in_grass/shiny/creeper0}
execute @a[score_mig_attractrepel=3,tag=rock_tunnel,score_mig_crouch_timer_min=666,score_mig_crouch_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel=3,tag=rock_tunnel,score_mig_crouch_timer_min=666,score_mig_crouch_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] {"text":"§b§l✧§aCreeper Spawned§b§l✧"}
execute @a[score_mig_attractrepel=3,tag=rock_tunnel,score_mig_crouch_timer_min=666,score_mig_crouch_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~-1 ~ cobblestone /tellraw @a[score_mig_attractrepel=3,tag=rock_tunnel,score_mig_crouch_timer_min=666,score_mig_crouch_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] {"text":"§b§l✧§aCreeper Spawned§b§l✧"}
execute @a[score_mig_attractrepel=3,tag=rock_tunnel,score_mig_sprint_timer_min=666,score_mig_sprint_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /summon creeper ~ ~ ~ {CustomName:"§b§l✧§aCreeper§b§l✧",CustomNameVisible:0,PersistenceRequired:1,Tags:["shiny_1"],DeathLootTable:"pokeserver:mobs_in_grass/shiny/creeper0}
execute @a[score_mig_attractrepel=3,tag=rock_tunnel,score_mig_sprint_timer_min=666,score_mig_sprint_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~-1 ~ cobblestone /summon creeper ~ ~ ~ {CustomName:"§b§l✧§aCreeper§b§l✧",CustomNameVisible:0,PersistenceRequired:1,Tags:["shiny_1"],DeathLootTable:"pokeserver:mobs_in_grass/shiny/creeper0}
execute @a[score_mig_attractrepel=3,tag=rock_tunnel,score_mig_sprint_timer_min=666,score_mig_sprint_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel=3,tag=rock_tunnel,score_mig_sprint_timer_min=666,score_mig_sprint_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] {"text":"§b§l✧§aCreeper Spawned§b§l✧"}
execute @a[score_mig_attractrepel=3,tag=rock_tunnel,score_mig_sprint_timer_min=666,score_mig_sprint_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~-1 ~ cobblestone /tellraw @a[score_mig_attractrepel=3,tag=rock_tunnel,score_mig_sprint_timer_min=666,score_mig_sprint_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] {"text":"§b§l✧§aCreeper Spawned§b§l✧"}
execute @a[score_mig_attractrepel=3,tag=rock_tunnel,score_mig_walk_timer_min=666,score_mig_walk_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /summon creeper ~ ~ ~ {CustomName:"§b§l✧§aCreeper§b§l✧",CustomNameVisible:0,PersistenceRequired:1,Tags:["shiny_1"],DeathLootTable:"pokeserver:mobs_in_grass/shiny/creeper0}
execute @a[score_mig_attractrepel=3,tag=rock_tunnel,score_mig_walk_timer_min=666,score_mig_walk_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~-1 ~ cobblestone /summon creeper ~ ~ ~ {CustomName:"§b§l✧§aCreeper§b§l✧",CustomNameVisible:0,PersistenceRequired:1,Tags:["shiny_1"],DeathLootTable:"pokeserver:mobs_in_grass/shiny/creeper0}
execute @a[score_mig_attractrepel=3,tag=rock_tunnel,score_mig_walk_timer_min=666,score_mig_walk_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~-1 ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel=3,tag=rock_tunnel,score_mig_walk_timer_min=666,score_mig_walk_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] {"text":"§b§l✧§aCreeper Spawned§b§l✧"}
execute @a[score_mig_attractrepel=3,tag=rock_tunnel,score_mig_walk_timer_min=666,score_mig_walk_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~-1 ~ cobblestone /tellraw @a[score_mig_attractrepel=3,tag=rock_tunnel,score_mig_walk_timer_min=666,score_mig_walk_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] {"text":"§b§l✧§aCreeper Spawned§b§l✧"}
scoreboard players add @a[score_mig_attractrepel=3,tag=rock_tunnel,score_mig_crouch_timer_min=666,score_mig_crouch_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] mig_crouch_timer 5
scoreboard players add @a[score_mig_attractrepel=3,tag=rock_tunnel,score_mig_sprint_timer_min=666,score_mig_sprint_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] mig_sprint_timer 5
scoreboard players add @a[score_mig_attractrepel=3,tag=rock_tunnel,score_mig_walk_timer_min=666,score_mig_walk_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] mig_walk_timer 5