#NORMAL
execute @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=route_20,score_mig_dive_timer_min=490,score_mig_dive_timer=500] ~ ~ ~ detect ~ ~ ~ water * /summon guardian ~ ~ ~ {CustomName:"§3Guardian",CustomNameVisible:0}
execute @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=route_20,score_mig_dive_timer_min=490,score_mig_dive_timer=500] ~ ~ ~ detect ~ ~ ~ water * /tellraw @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=route_20,score_mig_dive_timer_min=490,score_mig_dive_timer=500] {"text":"§3Guardian Spawned"}
execute @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=route_20,score_mig_swim_timer_min=490,score_mig_swim_timer=500] ~ ~ ~ detect ~ ~ ~ water * /summon guardian ~ ~ ~ {CustomName:"§3Guardian",CustomNameVisible:0}
execute @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=route_20,score_mig_swim_timer_min=490,score_mig_swim_timer=500] ~ ~ ~ detect ~ ~ ~ water * /tellraw @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=route_20,score_mig_swim_timer_min=490,score_mig_swim_timer=500] {"text":"§3Guardian Spawned"}
scoreboard players add @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=route_20,score_mig_dive_timer_min=490,score_mig_dive_timer=500] mig_dive_timer 10
scoreboard players add @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=route_20,score_mig_swim_timer_min=490,score_mig_swim_timer=500] mig_swim_timer 10
#ATTRACT
execute @a[score_mig_attractrepel_min=1,tag=route_20,score_mig_dive_timer_min=400,score_mig_dive_timer=500] ~ ~ ~ detect ~ ~ ~ water * /summon guardian ~ ~ ~ {CustomName:"§3Guardian",CustomNameVisible:0}
execute @a[score_mig_attractrepel_min=1,tag=route_20,score_mig_dive_timer_min=400,score_mig_dive_timer=500] ~ ~ ~ detect ~ ~ ~ water * /tellraw @a[score_mig_attractrepel_min=1,tag=route_20,score_mig_dive_timer_min=400,score_mig_dive_timer=500] {"text":"§3Guardian Spawned"}
execute @a[score_mig_attractrepel_min=1,tag=route_20,score_mig_swim_timer_min=400,score_mig_swim_timer=500] ~ ~ ~ detect ~ ~ ~ water * /summon guardian ~ ~ ~ {CustomName:"§3Guardian",CustomNameVisible:0}
execute @a[score_mig_attractrepel_min=1,tag=route_20,score_mig_swim_timer_min=400,score_mig_swim_timer=500] ~ ~ ~ detect ~ ~ ~ water * /tellraw @a[score_mig_attractrepel_min=1,tag=route_20,score_mig_swim_timer_min=400,score_mig_swim_timer=500] {"text":"§3Guardian Spawned"}
scoreboard players add @a[score_mig_attractrepel_min=1,tag=route_20,score_mig_dive_timer_min=400,score_mig_dive_timer=500] mig_dive_timer 100
scoreboard players add @a[score_mig_attractrepel_min=1,tag=route_20,score_mig_swim_timer_min=400,score_mig_swim_timer=500] mig_swim_timer 100
#REPEL
execute @a[score_mig_attractrepel=-1,tag=route_20,score_mig_dive_timer_min=495,score_mig_dive_timer=500] ~ ~ ~ detect ~ ~ ~ water * /summon guardian ~ ~ ~ {CustomName:"§3Guardian",CustomNameVisible:0}
execute @a[score_mig_attractrepel=-1,tag=route_20,score_mig_dive_timer_min=495,score_mig_dive_timer=500] ~ ~ ~ detect ~ ~ ~ water * /tellraw @a[score_mig_attractrepel=-1,tag=route_20,score_mig_dive_timer_min=495,score_mig_dive_timer=500] {"text":"§3Guardian Spawned"}
execute @a[score_mig_attractrepel=-1,tag=route_20,score_mig_swim_timer_min=495,score_mig_swim_timer=500] ~ ~ ~ detect ~ ~ ~ water * /summon guardian ~ ~ ~ {CustomName:"§3Guardian",CustomNameVisible:0}
execute @a[score_mig_attractrepel=-1,tag=route_20,score_mig_swim_timer_min=495,score_mig_swim_timer=500] ~ ~ ~ detect ~ ~ ~ water * /tellraw @a[score_mig_attractrepel=-1,tag=route_20,score_mig_swim_timer_min=495,score_mig_swim_timer=500] {"text":"§3Guardian Spawned"}
scoreboard players add @a[score_mig_attractrepel=-1,tag=route_20,score_mig_dive_timer_min=495,score_mig_dive_timer=500] mig_dive_timer 10
scoreboard players add @a[score_mig_attractrepel=-1,tag=route_20,score_mig_swim_timer_min=495,score_mig_swim_timer=500] mig_swim_timer 10
#SHINY
execute @a[score_mig_attractrepel=3,tag=route_20,score_mig_dive_timer_min=666,score_mig_dive_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~ ~ water * /summon guardian ~ ~ ~ {CustomName:"§b§l✧§3Guardian§b§l✧",CustomNameVisible:0,PersistenceRequired:1,Tags:["shiny_1"],DeathLootTable:"pokeserver:mobs_in_grass/shiny/guardian0}
execute @a[score_mig_attractrepel=3,tag=route_20,score_mig_dive_timer_min=666,score_mig_dive_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~ ~ water * /tellraw @a[score_mig_attractrepel=3,tag=route_20,score_mig_dive_timer_min=666,score_mig_dive_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] {"text":"§b§l✧§3Guardian Spawned§b§l✧"}
execute @a[score_mig_attractrepel=3,tag=route_20,score_mig_swim_timer_min=666,score_mig_swim_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~ ~ water * /summon guardian ~ ~ ~ {CustomName:"§b§l✧§3Guardian§b§l✧",CustomNameVisible:0,PersistenceRequired:1,Tags:["shiny_1"],DeathLootTable:"pokeserver:mobs_in_grass/shiny/guardian0}
execute @a[score_mig_attractrepel=3,tag=route_20,score_mig_swim_timer_min=666,score_mig_swim_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~ ~ water * /tellraw @a[score_mig_attractrepel=3,tag=route_20,score_mig_swim_timer_min=666,score_mig_swim_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] {"text":"§b§l✧§3Guardian Spawned§b§l✧"}
scoreboard players add @a[score_mig_attractrepel=3,tag=route_20,score_mig_dive_timer_min=666,score_mig_dive_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] mig_dive_timer 5
scoreboard players add @a[score_mig_attractrepel=3,tag=route_20,score_mig_swim_timer_min=666,score_mig_swim_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] mig_swim_timer 5