#NORMAL
execute @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=seafoam_cave,score_mig_crouch_timer_min=140,score_mig_crouch_timer=150] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /summon polar_bear ~ ~ ~ {CustomName:"§fPolar Bear",CustomNameVisible:0,Passengers:[{id:polar_bear,Age:-999999}],Passengers:[{id:polar_bear,Age:-999999}]}
execute @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=seafoam_cave,score_mig_crouch_timer_min=140,score_mig_crouch_timer=150] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=seafoam_cave,score_mig_crouch_timer_min=140,score_mig_crouch_timer=150] {"text":"§fPolar Bear Spawned"}
execute @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=seafoam_cave,score_mig_sprint_timer_min=140,score_mig_sprint_timer=150] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /summon polar_bear ~ ~ ~ {CustomName:"§fPolar Bear",CustomNameVisible:0,Passengers:[{id:polar_bear,Age:-999999}]}
execute @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=seafoam_cave,score_mig_sprint_timer_min=140,score_mig_sprint_timer=150] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=seafoam_cave,score_mig_sprint_timer_min=140,score_mig_sprint_timer=150] {"text":"§fPolar Bear Spawned"}
execute @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=seafoam_cave,score_mig_walk_timer_min=140,score_mig_walk_timer=150] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /summon polar_bear ~ ~ ~ {CustomName:"§fPolar Bear",CustomNameVisible:0,Passengers:[{id:polar_bear,Age:-999999}]}
execute @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=seafoam_cave,score_mig_walk_timer_min=140,score_mig_walk_timer=150] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=seafoam_cave,score_mig_walk_timer_min=140,score_mig_walk_timer=150] {"text":"§fPolar Bear Spawned"}
scoreboard players add @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=seafoam_cave,score_mig_crouch_timer_min=140,score_mig_crouch_timer=150] mig_crouch_timer 10
scoreboard players add @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=seafoam_cave,score_mig_sprint_timer_min=140,score_mig_sprint_timer=150] mig_sprint_timer 10
scoreboard players add @a[score_mig_attractrepel_min=0,score_mig_attractrepel=0,tag=seafoam_cave,score_mig_walk_timer_min=140,score_mig_walk_timer=150] mig_walk_timer 10
#ATTRACT
execute @a[score_mig_attractrepel_min=1,tag=seafoam_cave,score_mig_crouch_timer_min=50,score_mig_crouch_timer=150] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /summon polar_bear ~ ~ ~ {CustomName:"§fPolar Bear",CustomNameVisible:0,Passengers:[{id:polar_bear,Age:-999999}]}
execute @a[score_mig_attractrepel_min=1,tag=seafoam_cave,score_mig_crouch_timer_min=50,score_mig_crouch_timer=150] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel_min=1,tag=seafoam_cave,score_mig_crouch_timer_min=50,score_mig_crouch_timer=150] {"text":"§fPolar Bear Spawned"}
execute @a[score_mig_attractrepel_min=1,tag=seafoam_cave,score_mig_sprint_timer_min=50,score_mig_sprint_timer=150] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /summon polar_bear ~ ~ ~ {CustomName:"§fPolar Bear",CustomNameVisible:0,Passengers:[{id:polar_bear,Age:-999999}]}
execute @a[score_mig_attractrepel_min=1,tag=seafoam_cave,score_mig_sprint_timer_min=50,score_mig_sprint_timer=150] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel_min=1,tag=seafoam_cave,score_mig_sprint_timer_min=50,score_mig_sprint_timer=150] {"text":"§fPolar Bear Spawned"}
execute @a[score_mig_attractrepel_min=1,tag=seafoam_cave,score_mig_walk_timer_min=50,score_mig_walk_timer=150] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /summon polar_bear ~ ~ ~ {CustomName:"§fPolar Bear",CustomNameVisible:0,Passengers:[{id:polar_bear,Age:-999999}]}
execute @a[score_mig_attractrepel_min=1,tag=seafoam_cave,score_mig_walk_timer_min=50,score_mig_walk_timer=150] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel_min=1,tag=seafoam_cave,score_mig_walk_timer_min=50,score_mig_walk_timer=150] {"text":"§fPolar Bear Spawned"}
scoreboard players add @a[score_mig_attractrepel_min=1,tag=seafoam_cave,score_mig_crouch_timer_min=50,score_mig_crouch_timer=150] mig_crouch_timer 100
scoreboard players add @a[score_mig_attractrepel_min=1,tag=seafoam_cave,score_mig_sprint_timer_min=50,score_mig_sprint_timer=150] mig_sprint_timer 100
scoreboard players add @a[score_mig_attractrepel_min=1,tag=seafoam_cave,score_mig_walk_timer_min=50,score_mig_walk_timer=150] mig_walk_timer 100
#REPEL
execute @a[score_mig_attractrepel=-1,tag=seafoam_cave,score_mig_crouch_timer_min=145,score_mig_crouch_timer=150] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /summon polar_bear ~ ~ ~ {CustomName:"§fPolar Bear",CustomNameVisible:0,Passengers:[{id:polar_bear,Age:-999999}]}
execute @a[score_mig_attractrepel=-1,tag=seafoam_cave,score_mig_crouch_timer_min=145,score_mig_crouch_timer=150] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel=-1,tag=seafoam_cave,score_mig_crouch_timer_min=145,score_mig_crouch_timer=150] {"text":"§fPolar Bear Spawned"}
execute @a[score_mig_attractrepel=-1,tag=seafoam_cave,score_mig_sprint_timer_min=145,score_mig_sprint_timer=150] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /summon polar_bear ~ ~ ~ {CustomName:"§fPolar Bear",CustomNameVisible:0,Passengers:[{id:polar_bear,Age:-999999}]}
execute @a[score_mig_attractrepel=-1,tag=seafoam_cave,score_mig_sprint_timer_min=145,score_mig_sprint_timer=150] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel=-1,tag=seafoam_cave,score_mig_sprint_timer_min=145,score_mig_sprint_timer=150] {"text":"§fPolar Bear Spawned"}
execute @a[score_mig_attractrepel=-1,tag=seafoam_cave,score_mig_walk_timer_min=145,score_mig_walk_timer=150] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /summon polar_bear ~ ~ ~ {CustomName:"§fPolar Bear",CustomNameVisible:0,Passengers:[{id:polar_bear,Age:-999999}]}
execute @a[score_mig_attractrepel=-1,tag=seafoam_cave,score_mig_walk_timer_min=145,score_mig_walk_timer=150] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel=-1,tag=seafoam_cave,score_mig_walk_timer_min=145,score_mig_walk_timer=150] {"text":"§fPolar Bear Spawned"}
scoreboard players add @a[score_mig_attractrepel=-1,tag=seafoam_cave,score_mig_crouch_timer_min=145,score_mig_crouch_timer=150] mig_crouch_timer 10
scoreboard players add @a[score_mig_attractrepel=-1,tag=seafoam_cave,score_mig_sprint_timer_min=145,score_mig_sprint_timer=150] mig_sprint_timer 10
scoreboard players add @a[score_mig_attractrepel=-1,tag=seafoam_cave,score_mig_walk_timer_min=145,score_mig_walk_timer=150] mig_walk_timer 10
#SHINY
execute @a[score_mig_attractrepel=3,tag=seafoam_cave,score_mig_crouch_timer_min=666,score_mig_crouch_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /summon polar_bear ~ ~ ~ {CustomName:"§b§l✧§fPolar Bear§b§l✧",CustomNameVisible:0,Passengers:[{id:polar_bear,Age:-999999}],PersistenceRequired:1,Tags:["shiny_1"],DeathLootTable:"pokeserver:mobs_in_grass/shiny/polar_bear0}
execute @a[score_mig_attractrepel=3,tag=seafoam_cave,score_mig_crouch_timer_min=666,score_mig_crouch_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel=3,tag=seafoam_cave,score_mig_crouch_timer_min=666,score_mig_crouch_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] {"text":"§b§l✧§fPolar Bear Spawned§b§l✧"}
execute @a[score_mig_attractrepel=3,tag=seafoam_cave,score_mig_sprint_timer_min=666,score_mig_sprint_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /summon polar_bear ~ ~ ~ {CustomName:"§b§l✧§fPolar Bear§b§l✧",CustomNameVisible:0,Passengers:[{id:polar_bear,Age:-999999}],PersistenceRequired:1,Tags:["shiny_1"],DeathLootTable:"pokeserver:mobs_in_grass/shiny/polar_bear0}
execute @a[score_mig_attractrepel=3,tag=seafoam_cave,score_mig_sprint_timer_min=666,score_mig_sprint_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel=3,tag=seafoam_cave,score_mig_sprint_timer_min=666,score_mig_sprint_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] {"text":"§b§l✧§fPolar Bear Spawned§b§l✧"}
execute @a[score_mig_attractrepel=3,tag=seafoam_cave,score_mig_walk_timer_min=666,score_mig_walk_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /summon polar_bear ~ ~ ~ {CustomName:"§b§l✧§fPolar Bear§b§l✧",CustomNameVisible:0,Passengers:[{id:polar_bear,Age:-999999}],PersistenceRequired:1,Tags:["shiny_1"],DeathLootTable:"pokeserver:mobs_in_grass/shiny/polar_bear0}
execute @a[score_mig_attractrepel=3,tag=seafoam_cave,score_mig_walk_timer_min=666,score_mig_walk_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~ ~ stained_hardened_clay color=cyan /tellraw @a[score_mig_attractrepel=3,tag=seafoam_cave,score_mig_walk_timer_min=666,score_mig_walk_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] {"text":"§b§l✧§fPolar Bear Spawned§b§l✧"}
scoreboard players add @a[score_mig_attractrepel=3,tag=seafoam_cave,score_mig_crouch_timer_min=666,score_mig_crouch_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] mig_crouch_timer 5
scoreboard players add @a[score_mig_attractrepel=3,tag=seafoam_cave,score_mig_sprint_timer_min=666,score_mig_sprint_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] mig_sprint_timer 5
scoreboard players add @a[score_mig_attractrepel=3,tag=seafoam_cave,score_mig_walk_timer_min=666,score_mig_walk_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] mig_walk_timer 5