#ATTRACT
execute @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_crouch_timer_min=600,score_mig_crouch_timer=650] ~ ~ ~ detect ~ ~ ~ tallgrass type=tall_grass /summon vex ~ ~ ~ {CustomName:"§3Vex",CustomNameVisible:0}
execute @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_crouch_timer_min=600,score_mig_crouch_timer=650] ~ ~ ~ detect ~ ~ ~ tallgrass type=tall_grass /tellraw @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_crouch_timer_min=600,score_mig_crouch_timer=650] {"text":"§3Vex Spawned"}
execute @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_sprint_timer_min=600,score_mig_sprint_timer=650] ~ ~ ~ detect ~ ~ ~ tallgrass type=tall_grass /summon vex ~ ~ ~ {CustomName:"§3Vex",CustomNameVisible:0}
execute @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_sprint_timer_min=600,score_mig_sprint_timer=650] ~ ~ ~ detect ~ ~ ~ tallgrass type=tall_grass /tellraw @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_sprint_timer_min=600,score_mig_sprint_timer=650] {"text":"§3Vex Spawned"}
execute @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_walk_timer_min=600,score_mig_walk_timer=650] ~ ~ ~ detect ~ ~ ~ tallgrass type=tall_grass /summon vex ~ ~ ~ {CustomName:"§3Vex",CustomNameVisible:0}
execute @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_walk_timer_min=600,score_mig_walk_timer=650] ~ ~ ~ detect ~ ~ ~ tallgrass type=tall_grass /tellraw @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_walk_timer_min=600,score_mig_walk_timer=650] {"text":"§3Vex Spawned"}
scoreboard players add @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_crouch_timer_min=600,score_mig_crouch_timer=650] mig_crouch_timer 100
scoreboard players add @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_sprint_timer_min=600,score_mig_sprint_timer=650] mig_sprint_timer 100
scoreboard players add @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_walk_timer_min=600,score_mig_walk_timer=650] mig_walk_timer 100
#SHINY
execute @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_crouch_timer_min=666,score_mig_crouch_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~ ~ tallgrass type=tall_grass /summon vex ~ ~ ~ {CustomName:"§b§l✧§3Vex§b§l✧",CustomNameVisible:0,PersistenceRequired:1,Tags:["shiny_1"],DeathLootTable:"pokeserver:mobs_in_grass/shiny/vex0}
execute @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_crouch_timer_min=666,score_mig_crouch_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~ ~ tallgrass type=tall_grass /tellraw @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_crouch_timer_min=666,score_mig_crouch_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] {"text":"§b§l✧§3Vex Spawned§b§l✧"}
execute @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_sprint_timer_min=666,score_mig_sprint_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~ ~ tallgrass type=tall_grass /summon vex ~ ~ ~ {CustomName:"§b§l✧§3Vex§b§l✧",CustomNameVisible:0,PersistenceRequired:1,Tags:["shiny_1"],DeathLootTable:"pokeserver:mobs_in_grass/shiny/vex0}
execute @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_sprint_timer_min=666,score_mig_sprint_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~ ~ tallgrass type=tall_grass /tellraw @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_sprint_timer_min=666,score_mig_sprint_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] {"text":"§b§l✧§3Vex Spawned§b§l✧"}
execute @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_walk_timer_min=666,score_mig_walk_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~ ~ tallgrass type=tall_grass /summon vex ~ ~ ~ {CustomName:"§b§l✧§3Vex§b§l✧",CustomNameVisible:0,PersistenceRequired:1,Tags:["shiny_1"],DeathLootTable:"pokeserver:mobs_in_grass/shiny/vex0}
execute @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_walk_timer_min=666,score_mig_walk_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] ~ ~ ~ detect ~ ~ ~ tallgrass type=tall_grass /tellraw @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_walk_timer_min=666,score_mig_walk_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] {"text":"§b§l✧§3Vex Spawned§b§l✧"}
scoreboard players add @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_crouch_timer_min=666,score_mig_crouch_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] mig_crouch_timer 5
scoreboard players add @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_sprint_timer_min=666,score_mig_sprint_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] mig_sprint_timer 5
scoreboard players add @a[score_mig_attractrepel_min=1,score_mig_attractrepel=1,tag=route_8,score_mig_walk_timer_min=666,score_mig_walk_timer=666,score_mig_shinyness_min=666,score_mig_shinyness=666] mig_walk_timer 5